apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-image-deployment
  labels:
    app: demo-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-image
  template:
    metadata:
      labels:
        app: demo-image
    spec:
      containers:
      - name: nodeserver
        image: kittu1985/demo-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: demo-image-service
spec:
  selector:
    app: demo-image 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
    nodePort: 31110
